### ISSUE TITLE
Error During the parse classes generation, when a xsd with choice element

### ISSUE THREAD

**Issue by thiagodemoura** [mklemm/jaxb-rich-contract-plugin#27]
Hi,
## I´m trying to generate some parse classes. When the Fluient plugin try to generate a file that has the following structure it brokes. you could check the error bellow...

```
<xs:complexType name="HyperFunStageType">
    <xs:complexContent>
        <xs:extension base="StageType">
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="ProcessInputVariable" type="InputVariableType"
                    minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="ProcessOutputVariable" type="OutputVariableType"
                    minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="PipelineInputVariable" type="InputVariableType"
                    minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="PipelineOutputVariable" type="OutputVariableType"
                    minOccurs="0" maxOccurs="unbounded" />
            </xs:choice>
            <xs:attribute name="Type" type="StageEnum" use="required"
                fixed="HyperFun" />
            <xs:attribute name="Depends" type="xs:int" />
        </xs:extension>
    </xs:complexContent>
</xs:complexType>
```

---

Maven Error

`at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:196)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.lang.ClassCastException: com.sun.tools.xjc.model.CElementInfo cannot be cast to com.sun.tools.xjc.model.CClassInfo
        at com.kscs.util.plugins.xjc.BuilderGenerator.generateBuilderMemberOverride(BuilderGenerator.java:383)
        at com.kscs.util.plugins.xjc.BuilderGenerator.generateBuilderMemberOverrides(BuilderGenerator.java:715)
        at com.kscs.util.plugins.xjc.BuilderGenerator.buildProperties(BuilderGenerator.java:687)
        at com.kscs.util.plugins.xjc.FluentBuilderPlugin.run(FluentBuilderPlugin.java:121)
        at com.sun.tools.xjc.model.Model.generateCode(Model.java:292)
        at org.jvnet.mjiip.v_2_2.XJC22Mojo.generateCode(XJC22Mojo.java:66)
        at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:41)
        at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
        at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:505)
        at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:328)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
`

---

Is there any work around that i could use to solve this?

**Comment by mklemm** [comment]
Hi,
this could actually be a bug, most likely caused by the way the <choice> is used here - though your version is perfectly OK normally, provided "StageType" is available. One suggestion is to try to wrap the <choice> inside another <sequence>. I'll try to investigate what is going wrong, but it would be helpful if you could provide the complete XSD, binding-config (if you have one), and the arguments with which you are calling XJC.
